spring.application.name=forgeoj-judge-worker
spring.main.web-application-type=none
spring.rabbitmq.listener.simple.acknowledge-mode=manual
spring.rabbitmq.listener.simple.prefetch=1
forgeoj.worker.consumer.enabled=false
forgeoj.worker.sandbox.enabled=false
forgeoj.worker.docker.executable=docker
