/* Copyright 2026 池也; SPDX-License-Identifier: Apache-2.0 */
package com.forgeoj.api.classroom;

import java.time.LocalDateTime;
import java.util.*;
import org.apache.ibatis.annotations.*;

@Mapper
public interface AssignmentMapper {
    record Row(String id,String classroomId,long createdBy,String title,String description,String status,LocalDateTime startsAt,LocalDateTime deadlineAt,LocalDateTime startedAt,LocalDateTime endedAt,String closeReason,boolean acceptExistingAc,boolean allowLate,String solutionPolicy,long version) {}
    record Problem(long problemId,long judgeVersionId,String problemSlug,String metadataText,String solutionSnapshotId,int ordinal) {}
    record Candidate(long problemId,long judgeVersionId,String problemSlug,String metadataText,String solutionSnapshotId) {}
    record Proof(String submissionId,LocalDateTime acceptedAt,LocalDateTime finishedAt) {}
    @Select("SELECT EXISTS(SELECT 1 FROM public_problem_governance WHERE problem_id=#{problem} AND data_invalid=TRUE)") boolean invalid(long problem);
    String COLUMNS="id,classroom_id,created_by,title,description,status,starts_at,deadline_at,started_at,ended_at,close_reason,accept_existing_ac,allow_late,solution_policy,version";
    @Select("SELECT id FROM assignment_policy_fence WHERE id=1 FOR UPDATE") int fence();
    @Select("SELECT UTC_TIMESTAMP(6)") LocalDateTime now();
    @Select("SELECT TIMESTAMPDIFF(SECOND,UTC_TIMESTAMP(6),CURRENT_TIMESTAMP(6))") int databaseOffsetSeconds();
    @Select("SELECT "+COLUMNS+" FROM classroom_assignment WHERE id=#{id} AND classroom_id=#{room} FOR UPDATE") Optional<Row> lock(@Param("room") String room,@Param("id") String id);
    @Select("SELECT "+COLUMNS+" FROM classroom_assignment WHERE created_by=#{user} AND client_request_id=#{request}") Optional<Row> request(@Param("user") long user,@Param("request") String request);
    @Select("SELECT "+COLUMNS+" FROM classroom_assignment WHERE classroom_id=#{room} ORDER BY created_at DESC,id DESC LIMIT #{size} OFFSET #{offset}") List<Row> list(@Param("room") String room,@Param("size") int size,@Param("offset") long offset);
    @Select("SELECT COUNT(*) FROM classroom_assignment WHERE classroom_id=#{room}") long count(String room);
    String VISIBLE=" FROM classroom_assignment a WHERE a.classroom_id=#{room} AND (#{teacher} OR EXISTS(SELECT 1 FROM assignment_participant m WHERE m.assignment_id=a.id AND m.user_id=#{user}) OR #{member} AND a.status='SCHEDULED')";
    @Select("SELECT COUNT(*)"+VISIBLE) long visibleCount(@Param("room") String room,@Param("user") long user,@Param("member") boolean member,@Param("teacher") boolean teacher);
    @Select("SELECT "+COLUMNS+VISIBLE+" ORDER BY a.created_at DESC,a.id DESC LIMIT #{size} OFFSET #{offset}") List<Row> visible(@Param("room") String room,@Param("user") long user,@Param("member") boolean member,@Param("teacher") boolean teacher,@Param("size") int size,@Param("offset") long offset);
    @Update("UPDATE classroom_assignment SET version=version+1 WHERE id=#{id} AND version=#{version}") int bump(@Param("id") String id,@Param("version") long version);
    @Update("UPDATE classroom_assignment SET status='ACTIVE',ended_at=NULL,close_reason=NULL WHERE id=#{id} AND status='ENDED' AND close_reason='硬截止'") int extendNaturalEnd(String id);
    @Select("SELECT COUNT(*) FROM problem WHERE id=#{problem} AND status='ACTIVE' AND (scope='PUBLIC' OR scope='CLASSROOM' AND classroom_id=#{room})") int activeProblem(@Param("problem") long problem,@Param("room") String room);
    @Select("SELECT solution_idea AS idea,solution_code AS code FROM content_validation_snapshot WHERE id=#{snapshot}") ClassroomProblemMapper.Solution privateSolution(String snapshot);
    @Select("SELECT creation_sha256 FROM classroom_assignment WHERE id=#{id}") String creationHash(String id);
    @Insert("INSERT INTO classroom_assignment(id,classroom_id,created_by,client_request_id,creation_sha256,title,description,deadline_at,accept_existing_ac,allow_late,solution_policy) VALUES(#{id},#{room},#{user},#{request},#{hash},#{title},#{description},#{deadline},#{existing},#{late},#{policy})")
    int create(@Param("id") String id,@Param("room") String room,@Param("user") long user,@Param("request") String request,@Param("hash") String hash,@Param("title") String title,@Param("description") String description,@Param("deadline") LocalDateTime deadline,@Param("existing") boolean existing,@Param("late") boolean late,@Param("policy") String policy);
    @Update("UPDATE classroom_assignment SET title=#{title},description=#{description},deadline_at=#{deadline},accept_existing_ac=#{existing},allow_late=#{late},solution_policy=#{policy},version=version+1 WHERE id=#{id} AND version=#{version}")
    int edit(@Param("id") String id,@Param("version") long version,@Param("title") String title,@Param("description") String description,@Param("deadline") LocalDateTime deadline,@Param("existing") boolean existing,@Param("late") boolean late,@Param("policy") String policy);
    @Update("UPDATE classroom_assignment SET status='DRAFT',starts_at=NULL,version=version+1 WHERE id=#{id}") int unschedule(String id);
    @Update("UPDATE classroom_assignment SET status=#{status},starts_at=#{start},started_at=#{actual},version=version+1 WHERE id=#{id}") int publish(@Param("id") String id,@Param("status") String status,@Param("start") LocalDateTime start,@Param("actual") LocalDateTime actual);
    @Update("UPDATE classroom_assignment SET status=#{status},ended_at=#{at},close_reason=#{reason},version=version+1 WHERE id=#{id} AND status IN ('DRAFT','SCHEDULED','ACTIVE')") int close(@Param("id") String id,@Param("status") String status,@Param("at") LocalDateTime at,@Param("reason") String reason);
    @Select("SELECT DISTINCT classroom_id FROM classroom_assignment WHERE (status='SCHEDULED' AND starts_at<=UTC_TIMESTAMP(6)) OR (status='ACTIVE' AND allow_late=FALSE AND deadline_at<=UTC_TIMESTAMP(6)) ORDER BY classroom_id LIMIT 50") List<String> dueRooms();
    @Select("SELECT "+COLUMNS+" FROM classroom_assignment WHERE classroom_id=#{room} AND status IN ('DRAFT','SCHEDULED','ACTIVE') ORDER BY id FOR UPDATE") List<Row> open(String room);
    @Select("SELECT p.problem_id,p.judge_version_id,p.problem_slug,p.metadata_text,p.solution_snapshot_id,p.ordinal FROM assignment_draft_problem p JOIN classroom_assignment a ON a.id=p.assignment_id WHERE a.id=#{id} AND a.started_at IS NULL UNION ALL SELECT p.problem_id,p.judge_version_id,p.problem_slug,p.metadata_text,p.solution_snapshot_id,p.ordinal FROM assignment_problem p JOIN classroom_assignment a ON a.id=p.assignment_id WHERE a.id=#{id} AND a.started_at IS NOT NULL ORDER BY ordinal") List<Problem> problems(String id);
    @Select("SELECT p.id AS problemId,j.id AS judgeVersionId,p.slug AS problemSlug,CASE WHEN p.scope='CLASSROOM' THEN v.metadata_text ELSE JSON_OBJECT('title',p.title,'statement',p.statement_text,'inputDescription',p.input_description,'outputDescription',p.output_description,'samples',p.public_samples_json,'originType','PUBLIC','sourceUrl',NULL,'licenseStatement',NULL,'timeLimitMs',j.time_limit_ms,'memoryLimitMb',j.memory_limit_mb,'outputLimitBytes',j.output_limit_bytes) END AS metadataText,c.snapshot_id AS solutionSnapshotId FROM problem p JOIN problem_judge_version j ON j.id=p.current_judge_version_id LEFT JOIN classroom_problem c ON c.problem_id=p.id LEFT JOIN content_validation_snapshot v ON v.id=c.snapshot_id WHERE p.slug=#{slug} AND p.status='ACTIVE' AND (p.scope='PUBLIC' OR p.scope='CLASSROOM' AND p.classroom_id=#{room}) FOR SHARE") Optional<Candidate> candidate(@Param("room") String room,@Param("slug") String slug);
    @Insert("INSERT INTO assignment_draft_problem(assignment_id,problem_id,judge_version_id,problem_slug,metadata_text,solution_snapshot_id,ordinal) VALUES(#{id},#{p.problemId},#{p.judgeVersionId},#{p.problemSlug},#{p.metadataText},#{p.solutionSnapshotId},#{ordinal})") int problem(@Param("id") String id,@Param("p") Candidate p,@Param("ordinal") int ordinal);
    @Delete("DELETE FROM assignment_draft_problem WHERE assignment_id=#{id}") int removeProblems(String id);
    @Insert("INSERT INTO assignment_problem SELECT * FROM assignment_draft_problem WHERE assignment_id=#{id}") int freeze(String id);
    @Insert("INSERT INTO assignment_participant(assignment_id,classroom_id,user_id,joined_at) SELECT #{id},classroom_id,user_id,#{at} FROM classroom_member WHERE classroom_id=#{room} AND status='ACTIVE'") int snapshot(@Param("id") String id,@Param("room") String room,@Param("at") LocalDateTime at);
    @Insert("INSERT INTO assignment_participant(assignment_id,classroom_id,user_id,joined_at) VALUES(#{id},#{room},#{user},#{at})") int participant(@Param("id") String id,@Param("room") String room,@Param("user") long user,@Param("at") LocalDateTime at);
    @Select("SELECT EXISTS(SELECT 1 FROM assignment_participant WHERE assignment_id=#{id} AND user_id=#{user})") boolean participates(@Param("id") String id,@Param("user") long user);
    @Select("SELECT user_id FROM assignment_participant WHERE assignment_id=#{id} ORDER BY user_id") List<Long> participants(String id);
    @Insert("INSERT IGNORE INTO assignment_precompletion(assignment_id,user_id,problem_id,judge_version_id,submission_id) SELECT #{id},x.user_id,x.problem_id,x.judge_version_id,x.id FROM (SELECT s.*,ROW_NUMBER() OVER(PARTITION BY s.user_id,s.problem_id ORDER BY s.finished_at,s.id) AS rn FROM submission s JOIN assignment_problem p ON p.problem_id=s.problem_id AND p.judge_version_id=s.judge_version_id AND p.assignment_id=#{id} JOIN assignment_participant m ON m.assignment_id=#{id} AND m.user_id=s.user_id WHERE s.processing_status='FINISHED' AND s.verdict='AC' AND s.finished_at<=#{cutoff} AND (#{user} IS NULL OR s.user_id=#{user})) x WHERE x.rn=1") int precomplete(@Param("id") String id,@Param("user") Long user,@Param("cutoff") LocalDateTime cutoff);
    @Select("SELECT submission_id FROM assignment_precompletion WHERE assignment_id=#{id} AND user_id=#{user} AND problem_id=#{problem}") Optional<String> precompleted(@Param("id") String id,@Param("user") long user,@Param("problem") long problem);
    @Select("SELECT COUNT(*) FROM assignment_attempt WHERE assignment_id=#{id} AND user_id=#{user} AND problem_id=#{problem}") int attempts(@Param("id") String id,@Param("user") long user,@Param("problem") long problem);
    @Select("SELECT a.submission_id,a.accepted_at,TIMESTAMPADD(SECOND,-TIMESTAMPDIFF(SECOND,UTC_TIMESTAMP(6),CURRENT_TIMESTAMP(6)),s.finished_at) AS finishedAt FROM assignment_attempt a JOIN submission s ON s.id=a.submission_id AND s.user_id=a.user_id AND s.problem_id=a.problem_id AND s.judge_version_id=a.judge_version_id WHERE a.assignment_id=#{id} AND a.user_id=#{user} AND a.problem_id=#{problem} AND s.processing_status='FINISHED' AND s.verdict='AC' ORDER BY a.accepted_at,a.submission_id LIMIT 1") Optional<Proof> ac(@Param("id") String id,@Param("user") long user,@Param("problem") long problem);
    @Select("SELECT a.submission_id,a.accepted_at,TIMESTAMPADD(SECOND,-TIMESTAMPDIFF(SECOND,UTC_TIMESTAMP(6),CURRENT_TIMESTAMP(6)),s.finished_at) AS finishedAt FROM assignment_attempt a JOIN submission s ON s.id=a.submission_id AND s.user_id=a.user_id AND s.problem_id=a.problem_id AND s.judge_version_id=a.judge_version_id WHERE a.assignment_id=#{id} AND a.user_id=#{user} AND a.problem_id=#{problem} AND s.processing_status='FINISHED' AND s.verdict='AC' ORDER BY s.finished_at,a.submission_id LIMIT 1") Optional<Proof> firstAc(@Param("id") String id,@Param("user") long user,@Param("problem") long problem);
    @Select("SELECT EXISTS(SELECT 1 FROM assignment_attempt WHERE submission_id=#{submission} AND assignment_id=#{id} AND user_id=#{user} AND problem_id=#{problem})") boolean linked(@Param("submission") String submission,@Param("id") String id,@Param("user") long user,@Param("problem") long problem);
    @Insert("INSERT INTO assignment_attempt(submission_id,assignment_id,user_id,problem_id,judge_version_id,accepted_at) VALUES(#{submission},#{id},#{user},#{problem},#{judge},#{at})") int attempt(@Param("submission") String submission,@Param("id") String id,@Param("user") long user,@Param("problem") long problem,@Param("judge") long judge,@Param("at") LocalDateTime at);
    @Select("SELECT "+"a.id,a.classroom_id,a.created_by,a.title,a.description,a.status,a.starts_at,a.deadline_at,a.started_at,a.ended_at,a.close_reason,a.accept_existing_ac,a.allow_late,a.solution_policy,a.version"+" FROM classroom_assignment a JOIN assignment_participant m ON m.assignment_id=a.id AND m.user_id=#{user} JOIN assignment_problem p ON p.assignment_id=a.id WHERE p.problem_id=#{problem} AND a.started_at IS NOT NULL AND a.status IN ('ACTIVE','ENDED') ORDER BY a.id") List<Row> restrictions(@Param("user") long user,@Param("problem") long problem);
    @Select("SELECT idea,source_code AS code FROM official_problem_solution WHERE judge_version_id=#{judge}") Optional<ClassroomProblemMapper.Solution> publicSolution(long judge);
    @Insert("INSERT INTO assignment_self_test(run_id,assignment_id,user_id,problem_id,judge_version_id) VALUES(#{run},#{id},#{user},#{problem},#{judge})") int selfTest(@Param("run") String run,@Param("id") String id,@Param("user") long user,@Param("problem") long problem,@Param("judge") long judge);
    @Select("SELECT EXISTS(SELECT 1 FROM assignment_self_test WHERE run_id=#{run} AND assignment_id=#{id} AND user_id=#{user} AND problem_id=#{problem})") boolean selfTestLinked(@Param("run") String run,@Param("id") String id,@Param("user") long user,@Param("problem") long problem);
}
