/* Copyright 2026 池也; SPDX-License-Identifier: Apache-2.0 */
package com.forgeoj.worker.selftest;

import java.util.*;
import org.apache.ibatis.annotations.*;

@Mapper
public interface SelfTestMapper {
    record Job(String id,String snapshotId,long ownerId,String processingStatus,long statusVersion,int attemptCount,int maxAttempts,int deliverySequence,String leaseOwner,String leaseToken,boolean leaseValid,boolean due) {}
    record Snapshot(String id,long ownerId,long problemId,String problemSlug,long judgeVersionId,String language,String sourceCode,String inputText,String sourceSha256,String inputSha256,long inputBytes,int timeLimitMs,int memoryLimitMb,long outputLimitBytes,String javaImageDigest,String comparisonRuleVersion,String sandboxPolicyVersion,String snapshotSha256) {}
    @Select("SELECT id,snapshot_id,owner_id,processing_status,status_version,attempt_count,max_attempts,delivery_sequence,lease_owner,lease_token,(lease_expires_at IS NOT NULL AND lease_expires_at>CURRENT_TIMESTAMP(6)) AS leaseValid,(next_attempt_at IS NULL OR next_attempt_at<=CURRENT_TIMESTAMP(6)) AS due FROM self_test_job WHERE id=#{id} FOR UPDATE") Optional<Job> lock(String id);
    @Select("SELECT user_id FROM user_judge_quota_lock WHERE user_id=#{owner} FOR UPDATE") Optional<Long> quota(long owner);
    @Select("SELECT (SELECT COUNT(*) FROM submission WHERE user_id=#{owner} AND processing_status='RUNNING')+(SELECT COUNT(*) FROM content_validation_job WHERE owner_id=#{owner} AND processing_status IN ('RUNNING','WAITING_RETRY'))+(SELECT COUNT(*) FROM self_test_job WHERE owner_id=#{owner} AND id<>#{id} AND processing_status IN ('RUNNING','WAITING_RETRY'))") int otherRunning(@Param("owner") long owner,@Param("id") String id);
    @Update("UPDATE self_test_job SET processing_status='RUNNING',status_version=status_version+1,attempt_count=attempt_count+1,lease_owner=#{worker},lease_token=#{token},lease_expires_at=TIMESTAMPADD(SECOND,#{seconds},CURRENT_TIMESTAMP(6)),next_attempt_at=NULL,started_at=COALESCE(started_at,CURRENT_TIMESTAMP(6)),last_failure_code=NULL WHERE id=#{id} AND status_version=#{version} AND processing_status IN ('QUEUED','WAITING_RETRY') AND attempt_count<max_attempts AND (next_attempt_at IS NULL OR next_attempt_at<=CURRENT_TIMESTAMP(6))") int claim(@Param("id") String id,@Param("version") long version,@Param("worker") String worker,@Param("token") String token,@Param("seconds") long seconds);
    @Insert("INSERT INTO self_test_attempt(id,job_id,attempt_no,lease_token,worker_id,lease_expires_at) SELECT #{attempt},id,attempt_count,lease_token,lease_owner,lease_expires_at FROM self_test_job WHERE id=#{id} AND lease_token=#{token} AND processing_status='RUNNING' AND lease_expires_at>CURRENT_TIMESTAMP(6)") int attempt(@Param("attempt") String attempt,@Param("id") String id,@Param("token") String token);
    @Update("UPDATE self_test_job SET lease_expires_at=TIMESTAMPADD(SECOND,#{seconds},CURRENT_TIMESTAMP(6)) WHERE id=#{id} AND processing_status='RUNNING' AND lease_token=#{token} AND lease_owner=#{worker} AND lease_expires_at>CURRENT_TIMESTAMP(6)") int heartbeat(@Param("id") String id,@Param("token") String token,@Param("worker") String worker,@Param("seconds") long seconds);
    @Update("UPDATE self_test_attempt a JOIN self_test_job j ON j.id=a.job_id SET a.heartbeat_at=CURRENT_TIMESTAMP(6),a.lease_expires_at=j.lease_expires_at WHERE a.id=#{attempt} AND a.job_id=#{id} AND a.lease_token=#{token} AND a.attempt_status='RUNNING' AND j.lease_token=#{token} AND j.processing_status='RUNNING' AND j.lease_expires_at>CURRENT_TIMESTAMP(6)") int attemptHeartbeat(@Param("attempt") String attempt,@Param("id") String id,@Param("token") String token);
    @Select("SELECT COUNT(*) FROM self_test_attempt WHERE id=#{attempt} AND job_id=#{id} AND lease_token=#{token} AND attempt_status='RUNNING' AND lease_expires_at>CURRENT_TIMESTAMP(6)") int activeAttempt(@Param("attempt") String attempt,@Param("id") String id,@Param("token") String token);
    @Update("UPDATE self_test_attempt SET attempt_status=#{status},failure_code=#{failure},finished_at=CURRENT_TIMESTAMP(6) WHERE job_id=#{id} AND lease_token=#{token} AND attempt_status='RUNNING'") int closeAttempt(@Param("id") String id,@Param("token") String token,@Param("status") String status,@Param("failure") String failure);
    @Insert("INSERT INTO self_test_output(job_id,snapshot_id,output_gzip,output_bytes,output_sha256) VALUES(#{id},#{snapshot},#{gzip},#{bytes},#{sha})") int output(@Param("id") String id,@Param("snapshot") String snapshot,@Param("gzip") byte[] gzip,@Param("bytes") long bytes,@Param("sha") String sha);
    @Update("UPDATE self_test_job SET processing_status='FINISHED',status_version=status_version+1,execution_result=#{result},lease_owner=NULL,lease_token=NULL,lease_expires_at=NULL,next_attempt_at=NULL,finished_at=CURRENT_TIMESTAMP(6),expires_at=TIMESTAMPADD(HOUR,24,CURRENT_TIMESTAMP(6)) WHERE id=#{id} AND processing_status='RUNNING' AND lease_token=#{token} AND lease_expires_at>CURRENT_TIMESTAMP(6)") int finish(@Param("id") String id,@Param("token") String token,@Param("result") String result);
    @Update("UPDATE self_test_job SET processing_status=#{status},status_version=status_version+1,lease_owner=NULL,lease_token=NULL,lease_expires_at=NULL,last_failure_code=#{failure},next_attempt_at=IF(#{status}='SYSTEM_ERROR',NULL,TIMESTAMPADD(SECOND,#{delay},CURRENT_TIMESTAMP(6))),finished_at=IF(#{status}='SYSTEM_ERROR',CURRENT_TIMESTAMP(6),NULL),expires_at=IF(#{status}='SYSTEM_ERROR',TIMESTAMPADD(HOUR,24,CURRENT_TIMESTAMP(6)),NULL),delivery_sequence=delivery_sequence+1 WHERE id=#{id} AND status_version=#{version}") int retry(@Param("id") String id,@Param("version") long version,@Param("status") String status,@Param("delay") long delay,@Param("failure") String failure);
    @Insert("INSERT INTO outbox_event(id,aggregate_type,aggregate_id,event_type,contract_version,sequence_no,payload,next_attempt_at) SELECT #{event},'SELF_TEST',id,#{type},1,delivery_sequence,JSON_OBJECT('taskId',id,'snapshotId',snapshot_id,'taskType','SELF_TEST','contractVersion',1),COALESCE(next_attempt_at,CURRENT_TIMESTAMP(6)) FROM self_test_job WHERE id=#{id}") int outbox(@Param("event") String event,@Param("id") String id,@Param("type") String type);
    @Select("SELECT id FROM self_test_job WHERE processing_status='RUNNING' AND lease_expires_at<=CURRENT_TIMESTAMP(6) ORDER BY lease_expires_at,id LIMIT 20") List<String> expired();
    @Select("SELECT s.id,s.owner_id,s.problem_id,s.problem_slug,s.judge_version_id,s.language,p.source_code,p.input_text,s.source_sha256,s.input_sha256,s.input_bytes,s.time_limit_ms,s.memory_limit_mb,s.output_limit_bytes,s.java_image_digest,s.comparison_rule_version,s.sandbox_policy_version,s.snapshot_sha256 FROM self_test_snapshot s JOIN self_test_payload p ON p.snapshot_id=s.id JOIN self_test_job j ON j.snapshot_id=s.id JOIN self_test_attempt a ON a.job_id=j.id WHERE j.id=#{id} AND j.processing_status='RUNNING' AND j.lease_token=#{token} AND j.lease_expires_at>CURRENT_TIMESTAMP(6) AND a.id=#{attempt} AND a.lease_token=#{token} AND a.attempt_status='RUNNING' AND a.lease_expires_at>CURRENT_TIMESTAMP(6)") Optional<Snapshot> snapshot(@Param("id") String id,@Param("token") String token,@Param("attempt") String attempt);
}
