# Copyright 2026 池也
# SPDX-License-Identifier: Apache-2.0
# Test harness only. Never give this image/socket to the production API.
FROM docker:29.8.0-cli@sha256:f5b8bb0333cfaa027640106e5f02e48b0a8e0c00f7165015f581d58783c76fcf AS docker-cli
FROM maven:3.9.14-eclipse-temurin-21@sha256:98819eb3745bd2007c3f1a19b59085c1fa3929aecb7dbfa431dfcf5a4f18ce3c
COPY --from=docker-cli /usr/local/bin/docker /usr/local/bin/docker
WORKDIR /workspace
ENTRYPOINT ["/bin/bash"]
